### ISSUE TITLE
Text Issue in Idea detail page

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-civic-europe#187]
https://github.com/liqd/a4-civic-europe/blob/f0d460dffd827203304f7b6b220492cd12a1fe2a/apps/ideas/models/sections/local_dimension_section.py#L18
https://github.com/liqd/a4-civic-europe/blob/5fc9b87da2041e3d26c78d7dc3d1febd036b51a5/apps/ideas/views.py#L188
https://github.com/liqd/a4-civic-europe/commit/c7b493b819281d9f35219a6760903bad45a980c4

**Comment by hello-kathi** [comment]
We need a Headline-Text change on the Idea Detail Page.
Instead of "How does your idea strengthen democracy and citizenship as a living practice?" there must be:
"How does your idea strengthen democracy and active citizenship at a local and community level?"
<img width="602" alt="Bildschirmfoto 2020-04-21 um 12 52 13" src="https://user-images.githubusercontent.com/52459078/79964899-a31b0900-848b-11ea-965d-63c8015371a0.png">
