### ISSUE TITLE
#3551 - [Civic Europe] Note on not saving the data in the Application From

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-civic-europe#319]
**URL:** https://ce-dev.liqd.net/ideas/create/module/idea-challenge-2020/
**important screensize:** *Both*
**device & browser:** *Safari and Chrome*
**Comment/Question:** *I don't know if you talked to Kathi about that, but none of the options on Zeplin had to do with this:*

![Screenshot 2020-12-24 at 10 59 21](https://user-images.githubusercontent.com/59610786/103081133-9f6df200-45d7-11eb-8bab-6ecd428de5c2.png)

**Comment by phillimorland** [comment]
@mcastro-lqd when writing issues can you make sure to add a brief description? stuff might seem obvious to you but isn't clear to others :) 
if it's the issue with button placement, it is above the continue button as otherwise it would mean moving the placement on the other screens as needs to appear on every page, please see image:
Would you prefer the writing in-between the buttons?
![Screenshot 2020-12-28 at 12 31 56](https://user-images.githubusercontent.com/5871230/103211516-b3339400-4908-11eb-9a93-0881eca31007.png)

**Comment by mcastro-lqd** [comment]
@phillimorland I thought the image was clearer than writing, https://zpl.io/aXl31r8 none of the options had a red text on the bottom and none of the options had red text outside the white box, that's why I mentioned "if you talked to Kathi..." cause it seemed too different. 

Sure, its fine to be on top if the "Back" buttons are aligned to the left.

**Comment by phillimorland** [comment]
@mcastro-lqd we were using the design that was in the story: https://taiga.liqd.net/project/liqd-liquid-software/us/3551?milestone=243
did you not add that?

**Comment by mcastro-lqd** [comment]
@phillimorland  Thats just Kathis briefing, the design was here https://taiga.liqd.net/project/liqd-liquid-software/task/3610

**Comment by phillimorland** [comment]
@mcastro-lqd ahhh thats really annoying that was in there, ok cheers for clearing up! and nice design! :)
i'll have to write a note in the story about leaving non relevant attachments in there
