### ISSUE TITLE
Styling text of 1-3 text column

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#416]
**URL:** https://ce-dev.liqd.net/200218-test-simple-page/
AND
https://civic-europe.eu/what-we-do/winners-2020/

I have a question:

So far, the 1 text column is centered and also with a centered text - and this somehow looks weird, especially if you mix the different columns:

![Bildschirmfoto 2021-02-25 um 13 44 04](https://user-images.githubusercontent.com/30862422/109155184-903e2880-776f-11eb-922c-28568acbc708.png)

There is also the option of putting two columns but just having one column there. Which also looks weird...

![Bildschirmfoto 2021-02-25 um 13 45 24](https://user-images.githubusercontent.com/30862422/109155353-bcf24000-776f-11eb-80d1-48baacc6d467.png)

...so, is this just the way it usually everywhere is? What do we think is the best to combine the different columns? Which version do we find the most appealling?

This is especially for @phillimorland and @mcastro-lqd . Could you give me any advice on this? I need to advice CE what to do about the 1 column block and how they should use it if they are using it together with other 2-3 columns

**Comment by hmkay** [comment]
And maybe the last bit doesn´t really look weird at all....or at least not weirder than the centered column?

**Comment by fuzzylogic2000** [comment]
It's meant to be used with the number of columns that it says. So, if they want to have two columns after one column, they need to add one column to a block where they chose one column and then a block where they chose and add two columns. So, every line should be a block with the number of columns that should be in it.

**Comment by mcastro-lqd** [comment]
@hmkay 

**- Regarding this page: https://ce-dev.liqd.net/200218-test-simple-page/**

From what I remember, I think that's why these columns were created: https://zpl.io/VqDxxAm

Maybe it's because everything must be editable on Wagtail. From my perspective, this should be also matter of common sense. Unfortunately, when we leave so many open options, these things can happen.  The 1 column option is something created for short texts + button, not for long texts. Long texts should never be centered.

**- Regarding this one: https://civic-europe.eu/what-we-do/winners-2020/**

I didn't do this layout but I imagine that it's because this page is divided in two main sections (Left and Right) and it makes sense that the tiles on the right side are also aligned to the left. Since some countries have only 1 project and others have 3, this will happen. A quick solution would be aligning the Countries Titles to the left, so the 1 project countries sections would keep aligned to the left. 

Other more complex option would be changing the order of these elements in a way that the country titles aren't clashing much with the project titles on top of the images like the example below:
![Screenshot-2021-02-25-at-15 20 11](https://user-images.githubusercontent.com/59610786/109168339-01390c80-777f-11eb-87fd-4f8cb5e106f9.jpg)
 
(I know that my example is not perfectly aligned, but I did this example super fast using a Screenshot on Photoshop just for a short explanation 🙈)

**Comment by hmkay** [comment]
@fuzzylogic2000 and @mcastro-lqd , Thank you so much for your answers! Now I get it  alot better and also understand it better.  And will get back to CE now. Thanks!

**Comment by phillimorland** [comment]
@mcastro-lqd  which project tiles? do you have a link? 
Also please bear in mind that they changed their minds about some of the styling after designs were confirmed, hence why text allignment and page width is different, means designs don't fit as nicely

**Comment by hmkay** [comment]
I will close this now, if there are any more questions on that, I will open it again. Thanks for your participation =)
